# Generated by Django 5.1.6 on 2025-03-28 00:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
                "db_table": "resume_analysis_resume",
            },
        ),
        migrations.CreateModel(
            name="ResumeContent",
            fields=[
                (
                    "resume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="resume_analysis.resume",
                    ),
                ),
                ("raw_text", models.TextField()),
                ("structured_data", models.JSONField(default=dict)),
                ("extracted_features", models.JSONField(default=dict, null=True)),
                ("last_processed", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Resume Content",
                "verbose_name_plural": "Resume Contents",
                "db_table": "resume_analysis_resumecontent",
            },
        ),
    ]
