# Generated by Django 5.1.6 on 2025-04-04 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_analysis", "0002_resumecontent_processing_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumecontent",
            name="upload_date",
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name="resumecontent",
            name="uploaded_by",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
