# Generated by Django 5.1.6 on 2025-06-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gmail_access_token",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gmail_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="gmail_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gmail_refresh_token",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gmail_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
