# Generated by Django 5.1.6 on 2025-07-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_profile_gmail_access_token_profile_gmail_connected_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gmail_fetch_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="gmail_fetch_interval",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_gmail_fetch",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
